spring.application.name=uno-game

# MySQL configuration
spring.datasource.url=jdbc:mysql://localhost:3306/uno_game?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=

spring.jpa.hibernate.ddl-auto=update

spring.jpa.show-sql=true

server.port=8083

server.servlet.session.cookie.same-site=none
server.servlet.session.cookie.secure=false